apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop-dev
  labels:
    project: roboshop
    component: frontend
    environment: dev
    versiono: v1
spec:
  containers:
  - name: frontend
    image: nginx