apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: roboshop
    component: frontend
    version: v1
    environment: development

spec:
  containers:
  - name: frontend
    image: nginx
    