apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80