apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 10
  selector:
    matchLabels:
      purpose: rs-demo
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl